# Generated by Django 5.2 on 2026-01-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lock_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pwd_error_count",
        ),
        migrations.AlterField(
            model_name="person",
            name="class_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="班级"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="用户类型"
            ),
        ),
    ]
