# Generated by Django 5.2 on 2026-01-17 16:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_is_locked_remove_user_lock_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceScan",
            fields=[],
            options={
                "verbose_name": "人脸识别",
                "verbose_name_plural": "人脸识别",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.person",),
        ),
        migrations.AlterField(
            model_name="person",
            name="class_name",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="班级"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="face_image",
            field=models.ImageField(
                default="",
                max_length=255,
                upload_to=core.models.face_upload_to,
                verbose_name="人脸照片",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="source_image_url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="源图片URL"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="用户类型",
            ),
        ),
    ]
